### ISSUE TITLE
Level Backup Preview crash

### ISSUE THREAD

**Issue by zhubenjamin** [HJfod/Backups#5]
Not sure which HJfod mod did this, but I think either this or BetterEdit.
I was previewing a level backup in the Backups button on one of my levels. I went to exit out of the backup viewer, by pressing pause and then the exit button. GD froze, and brought up a crash dialogue a second later.
[crash log](https://github.com/user-attachments/files/16149420/2024-07-09_15-21-03.log)

**Comment by HJfod** [comment]
This is a BetterEdit issue
